DROP TABLE IF EXISTS heroes_info;

CREATE TABLE heroes_info
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50),
    gender     VARCHAR(50),
    eye_color  VARCHAR(50),
    race       VARCHAR(50),
    hair_color VARCHAR(50),
    height     VARCHAR(50),
    publisher  VARCHAR(50),
    skin_color VARCHAR(50),
    alignment  VARCHAR(50),
    weight     INTEGER
);

SELECT *
FROM heroes_info hi;
DROP TABLE IF EXISTS heroes;
CREATE TABLE heroes
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50),
    gender     VARCHAR(50),
    eye_color  VARCHAR(50),
    race       VARCHAR(50),
    hair_color VARCHAR(50),
    height     DOUBLE PRECISION,
    publisher  VARCHAR(50),
    skin_color VARCHAR(50),
    alignment  VARCHAR(50),
    weight     INTEGER
);

INSERT INTO heroes(name, gender, eye_color, race, hair_color, height, publisher, skin_color, alignment, weight)
SELECT name,
       gender,
       eye_color,
       race,
       hair_color,
       to_number(replace(height, ',', '.'), '9999.99'),
       publisher,
       skin_color,
       alignment,
       weight
FROM heroes_info;

SELECT *
FROM heroes;

SELECT avg(height) AS average_height
FROM heroes
WHERE height > 0;

SELECT name AS max_height
FROM heroes
WHERE height = (SELECT max(height) FROM heroes);

SELECT name AS max_weight
FROM heroes
WHERE weight = (SELECT max(weight) FROM heroes);

SELECT gender, COUNT(*)
FROM heroes
GROUP BY gender;

SELECT alignment, COUNT(*)
FROM heroes
GROUP BY alignment;

SELECT publisher AS top5_publishers, COUNT(*)
FROM heroes
GROUP BY publisher
ORDER BY count DESC, publisher
LIMIT 5;

SELECT hair_color AS top3_hair_colors, COUNT(*)
FROM heroes
GROUP BY hair_color
ORDER BY count DESC, hair_color
LIMIT 3;

SELECT eye_color AS top_eye_color, COUNT(*)
FROM heroes
GROUP BY eye_color
ORDER BY count DESC, eye_color
LIMIT 1;


