CREATE TABLE Homework
(
id 		integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name 	VARCHAR(40) NOT NULL,
description VARCHAR(200)
);
CREATE TABLE Lesson
(
id		integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name	VARCHAR(40) NOT NULL,
updated_at TIMESTAMP DEFAULT NOW(),
homework_id INTEGER,
FOREIGN KEY (homework_id) REFERENCES Homework(id)
);
CREATE TABLE Schedule
(
id		integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name	VARCHAR(40) NOT NULL,
updated_at TIMESTAMP DEFAULT NOW()
);
CREATE TABLE Lesson_Schedule
(
lesson_id integer REFERENCES Lesson(id),
schedule_id integer REFERENCES Schedule(id)
);


