CREATE TABLE IF NOT EXISTS accounts
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid        VARCHAR(255) NOT NULL UNIQUE,
    iban       VARCHAR(34)  NOT NULL,
    balance    INTEGER      NOT NULL,
    person_id  INTEGER      NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    CONSTRAINT fk_person_id FOREIGN KEY (person_id) REFERENCES persons (id)
);