CREATE TYPE card_status AS ENUM ('active', 'expired');
CREATE TABLE IF NOT EXISTS cards
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid             VARCHAR(255) NOT NULL UNIQUE,
    pan             VARCHAR(16)  NOT NULL UNIQUE CHECK ( LENGTH(pan) = 16 ),
    account_id      INTEGER      NOT NULL,
    expiration_date DATE         NOT NULL,
    pin             VARCHAR(4) CHECK ( LENGTH(pin) = 4 ),
    cvv             VARCHAR(3) CHECK ( LENGTH(cvv) = 3 ),
    status          card_status  NOT NULL DEFAULT 'active',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    person_id       INTEGER      NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts (id),
    FOREIGN KEY (person_id) REFERENCES persons (id)
);